### ISSUE TITLE
line 95 of home.dart - Failed assertion: boolean expression must not be null - isDataChanged

### ISSUE THREAD

**Issue by marcelmenezes** [burhanrashid52/WhatTodo#4] opened 2018-09-17 13:01 UTC
Debugging on iPhone 5s, when I click to add a task, it opens the Add Task route.  And when then I press the upper "back" button, on home.dart line 95 (if (isDataChanged) {) It shows "Failed assertion: boolean expression must not be null"

It seems that you are not using the right way to get the value of "isDataChanged".

**Comment by burhanrashid52** [comment] 2018-10-28 06:16
The issue is fixed in v.0.2.0. WhatTodo is migrated to BLoC pattern.

**Closed by burhanrashid52** 2018-10-28 06:16 UTC
